using System.Diagnostics;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.Data.Sqlite;

namespace Mcpp.Indexing;

/// <summary>
/// Indexes C++ translation units using ClangXref.dll (native IndexDataConsumer)
/// and populates XrefDatabase with symbols, call graphs, and cross-references.
///
/// Reads compile_commands.json (generated by CMake, Bear, bt, or similar tools).
/// Runs as a background task -- Phases 1-3 serve immediately while this indexes.
///
/// Flag translation, PCH handling, and AST traversal are all inside the DLL.
/// This class orchestrates: parallel dispatch, priority queue, chunked DB flush,
/// and atomic DB swap.
/// </summary>
public sealed class CppIndexer
{
    private readonly XrefDatabase _db;
    private readonly string _repoRoot;
    private readonly string _compileCommandsPath;

    // Priority queue: files requested by MCP tools get indexed first
    private readonly System.Collections.Concurrent.ConcurrentQueue<string> _priorityQueue = new();
    private readonly System.Collections.Concurrent.ConcurrentDictionary<string, byte> _indexedFiles = new(StringComparer.OrdinalIgnoreCase);
    private Dictionary<string, CompileCommand>? _commandsByFile;

    public CppIndexer(XrefDatabase db, string repoRoot, string compileCommandsPath)
    {
        _db = db;
        _repoRoot = repoRoot;
        _compileCommandsPath = compileCommandsPath;
    }

    /// <summary>
    /// Request that a file be indexed ahead of the sequential queue.
    /// Accepts absolute or repo-relative paths. Safe to call from any thread.
    /// </summary>
    public void Prioritize(string filePath)
    {
        var normalized = NormalizeFilePath(filePath);
        if (!_indexedFiles.ContainsKey(normalized))
            _priorityQueue.Enqueue(normalized);
    }

    /// <summary>
    /// Runs the full indexing pass. Designed to be called on a background thread.
    /// Builds into a temporary DB file, then atomically replaces the live DB on success.
    ///
    /// Multi-instance safety: only one process indexes at a time. A lock file
    /// (xref.db.lock) prevents concurrent indexing. If another instance holds the
    /// lock, this instance watches for the DB to be swapped and reloads it.
    /// </summary>
    public void BuildIndex(CancellationToken ct = default)
    {
        if (!File.Exists(_compileCommandsPath))
        {
            _db.MarkError($"compile_commands.json not found at {_compileCommandsPath}. " +
                "Generate it with CMake (-DCMAKE_EXPORT_COMPILE_COMMANDS=ON), Bear, or bt.");
            return;
        }

        var commands = LoadCompileCommands();
        if (commands.Count == 0)
        {
            _db.MarkError("compile_commands.json is empty.");
            return;
        }

        // Build lookup by normalized file path for priority queue
        _commandsByFile = new Dictionary<string, CompileCommand>(StringComparer.OrdinalIgnoreCase);
        foreach (var cmd in commands)
        {
            var key = NormalizeFilePath(cmd.File);
            _commandsByFile.TryAdd(key, cmd);
        }

        // The DLL loads compile_commands.json from this directory
        var compileCommandsDir = Path.GetDirectoryName(Path.GetFullPath(_compileCommandsPath))!;

        // Log ClangXref version
        try
        {
            McpLogger.Log("CppIndex", $"Using {NativeIndexer.GetVersion()}");
        }
        catch (DllNotFoundException ex)
        {
            _db.MarkError($"ClangXref.dll not found: {ex.Message}. " +
                "Build with: msbuild src\\ClangXref\\ClangXref.vcxproj /p:Configuration=Release /p:Platform=x64");
            return;
        }

        // --- Multi-instance lock: only one process indexes at a time ---
        var lockPath = _db.DbPath + ".lock";
        var lockFile = TryAcquireIndexLock(lockPath);

        if (lockFile == null)
        {
            McpLogger.Log("CppIndex", "Another instance is indexing — waiting for it to finish...");
            WaitForSiblingIndex(ct);
            return;
        }

        try
        {
            BuildIndexCore(commands, compileCommandsDir, ct);
        }
        finally
        {
            ReleaseIndexLock(lockFile, lockPath);
        }
    }

    /// <summary>
    /// Tries to acquire the index lock file atomically. Returns the held FileStream
    /// on success, or null if another live process holds it.
    /// Reclaims stale locks left by crashed processes (dead PID).
    /// </summary>
    private static FileStream? TryAcquireIndexLock(string lockPath)
    {
        FileStream? TryCreate(string path)
        {
            try
            {
                var fs = new FileStream(path, FileMode.CreateNew, FileAccess.Write, FileShare.Read);
                var pidBytes = System.Text.Encoding.UTF8.GetBytes(Environment.ProcessId.ToString());
                fs.Write(pidBytes);
                fs.Flush();
                return fs;
            }
            catch (IOException)
            {
                return null;
            }
        }

        // Fast path: no lock file exists
        var lockFile = TryCreate(lockPath);
        if (lockFile != null)
            return lockFile;

        // Lock file exists — check if the holder is still alive
        try
        {
            var pidText = File.ReadAllText(lockPath).Trim();
            if (int.TryParse(pidText, out var pid))
            {
                try
                {
                    Process.GetProcessById(pid);
                    // Process is alive — another instance is actively indexing
                    McpLogger.Log("CppIndex", $"Lock held by PID {pid} (alive)");
                    return null;
                }
                catch (ArgumentException)
                {
                    // Process is dead — stale lock from a crash
                    McpLogger.Log("CppIndex", $"Stale lock (PID {pid} dead) — reclaiming", "WARN");
                }
            }
            else
            {
                McpLogger.Log("CppIndex", "Corrupt lock file — reclaiming", "WARN");
            }

            File.Delete(lockPath);
        }
        catch (Exception ex)
        {
            McpLogger.Log("CppIndex", $"Could not read lock file: {ex.Message}", "WARN");
            return null;
        }

        // Retry after reclaiming stale lock
        return TryCreate(lockPath);
    }

    private static void ReleaseIndexLock(FileStream lockFile, string lockPath)
    {
        try { lockFile.Dispose(); } catch { }
        try { File.Delete(lockPath); } catch { }
    }

    /// <summary>
    /// Called when another instance holds the index lock. Watches for xref.db to
    /// be updated (the sibling's SwapDatabase), then reloads it.
    /// Uses FileSystemWatcher with debounce to avoid redundant reloads.
    /// </summary>
    private void WaitForSiblingIndex(CancellationToken ct)
    {
        var dbPath = _db.DbPath;
        var dir = Path.GetDirectoryName(dbPath)!;
        var fileName = Path.GetFileName(dbPath);

        if (!Directory.Exists(dir))
            Directory.CreateDirectory(dir);

        using var watcher = new FileSystemWatcher(dir, fileName);
        watcher.NotifyFilter = NotifyFilters.LastWrite | NotifyFilters.CreationTime | NotifyFilters.Size;

        var swapDetected = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
        Timer? debounce = null;

        void OnChanged(object sender, FileSystemEventArgs e)
        {
            debounce?.Dispose();
            debounce = new Timer(_ => swapDetected.TrySetResult(), null, 500, Timeout.Infinite);
        }

        watcher.Changed += OnChanged;
        watcher.Created += OnChanged;
        watcher.EnableRaisingEvents = true;

        using var ctReg = ct.Register(() => swapDetected.TrySetCanceled());

        try
        {
            swapDetected.Task.Wait(ct);
        }
        catch (OperationCanceledException)
        {
            McpLogger.Log("CppIndex", "Cancelled while waiting for sibling index.");
            debounce?.Dispose();
            return;
        }
        catch (AggregateException ae) when (ae.InnerException is TaskCanceledException)
        {
            McpLogger.Log("CppIndex", "Cancelled while waiting for sibling index.");
            debounce?.Dispose();
            return;
        }

        debounce?.Dispose();
        McpLogger.Log("CppIndex", "Sibling finished indexing — reloading DB...");
        _db.Reload();
    }

    /// <summary>
    /// Core indexing logic, called while holding the lock file.
    /// </summary>
    private void BuildIndexCore(List<CompileCommand> commands, string compileCommandsDir,
        CancellationToken ct)
    {
        // Build into a temp DB -- the live DB continues serving queries until we swap.
        var tempDbPath = _db.DbPath + ".new";

        // Recovery: if a previous run was killed mid-index, adopt the orphaned
        // temp DB rather than discarding its work.
        if (File.Exists(tempDbPath))
        {
            var liveSize = File.Exists(_db.DbPath) ? new FileInfo(_db.DbPath).Length : 0;
            var tempSize = new FileInfo(tempDbPath).Length;
            if (tempSize > liveSize)
            {
                McpLogger.Log("CppIndex", $"Recovering orphaned temp DB ({tempSize / 1024 / 1024} MB)");
                _db.Close();
                SqliteConnection.ClearAllPools();
                File.Move(tempDbPath, _db.DbPath, overwrite: true);
                _db.Open();
                _db.MarkReady();
                _db.LoadCallGraph();
            }
            // Clean up temp files either way
            foreach (var ext in new[] { "", "-wal", "-shm" })
            {
                var f = tempDbPath + ext;
                if (File.Exists(f)) try { File.Delete(f); } catch { }
            }
        }

        foreach (var ext in new[] { "", "-wal", "-shm" })
        {
            var f = tempDbPath + ext;
            if (File.Exists(f)) File.Delete(f);
        }

        var tempDb = new XrefDatabase(tempDbPath);
        tempDb.Open();

        McpLogger.Log("CppIndex", $"Indexing {commands.Count} translation units...");
        tempDb.SetProgress(0, commands.Count);

        var sw = Stopwatch.StartNew();

        // Generate PCH files for all groups (one-time, before parallel indexing)
        var pchDir = Path.Combine(Path.GetDirectoryName(tempDbPath)!, "pch");
        Directory.CreateDirectory(pchDir);
        using (var pchSession = new XrefSession(compileCommandsDir, _repoRoot))
        {
            var pchCount = NativeIndexer.clang_xref_prepare_pch(pchSession.Handle, pchDir);
            McpLogger.Log("CppIndex", $"PCH: {pchCount} groups prepared in {pchDir}");
        }

        try
        {
            int errors = 0;
            int indexed = 0;
            var failedTUs = new System.Collections.Concurrent.ConcurrentBag<CompileCommand>();
            var stackOverflowTUs = new System.Collections.Concurrent.ConcurrentBag<CompileCommand>();

            var parallelism = Math.Max(1, Environment.ProcessorCount);
            McpLogger.Log("CppIndex", $"Parallel indexing: {parallelism} threads");

            // DB writer lock: parallel parse, serial DB flush.
            // Avoids accumulating ~25M objects in memory from ConcurrentBag.
            var dbLock = new object();

            // Process all TUs in parallel
            Parallel.ForEach(commands,
                new ParallelOptions { MaxDegreeOfParallelism = parallelism, CancellationToken = ct },
                // Thread-local XrefSession: each handle is NOT thread-safe
                () => new XrefSession(compileCommandsDir, _repoRoot),
                (cmd, state, session) =>
                {
                    // -- Priority fast-path: drain any user-requested files first --
                    while (_priorityQueue.TryDequeue(out var priorityFile))
                    {
                        if (_indexedFiles.ContainsKey(priorityFile)) continue;
                        if (_commandsByFile!.TryGetValue(priorityFile, out var priorityCmd))
                        {
                            McpLogger.Log("CppIndex", $"Priority: {Path.GetFileName(priorityFile)}");
                            var priorityRc = IndexAndFlush(session, priorityCmd, tempDb, dbLock, ref errors);
                            if (priorityRc < 0)
                            {
                                if (priorityRc == (int)NativeIndexer.IndexResult.ErrorStackOverflow)
                                    stackOverflowTUs.Add(priorityCmd);
                                else
                                    failedTUs.Add(priorityCmd);
                            }
                            // priorityFile is already normalized by Prioritize()
                            _indexedFiles.TryAdd(priorityFile, 0);
                            Interlocked.Increment(ref indexed);
                        }
                    }

                    var normalizedFile = NormalizeFilePath(cmd.File);
                    if (!_indexedFiles.TryAdd(normalizedFile, 0))
                        return session; // already indexed

                    var rc = IndexAndFlush(session, cmd, tempDb, dbLock, ref errors);
                    if (rc < 0)
                    {
                        if (rc == (int)NativeIndexer.IndexResult.ErrorStackOverflow)
                            stackOverflowTUs.Add(cmd);
                        else
                            failedTUs.Add(cmd);
                    }

                    var count = Interlocked.Increment(ref indexed);
                    if (count % 50 == 0)
                    {
                        tempDb.SetProgress(count, commands.Count);
                        McpLogger.Log("CppIndex", $"Progress: {count}/{commands.Count} ({errors} errors)");
                    }

                    return session;
                },
                session => session.Dispose());

            // -- Sequential retry of TUs that crashed during parallel pass --
            // Race-condition crashes are non-deterministic (LLVM thread-safety).
            // With no concurrent threads, these should all succeed.
            if (failedTUs.Count > 0)
            {
                McpLogger.Log("CppIndex", $"Retrying {failedTUs.Count} failed TUs sequentially...", "WARN");
                int retryErrors = 0;
                using var retrySession = new XrefSession(compileCommandsDir, _repoRoot);
                foreach (var cmd2 in failedTUs)
                {
                    ct.ThrowIfCancellationRequested();
                    var retryRc = IndexAndFlush(retrySession, cmd2, tempDb, dbLock, ref retryErrors);
                    if (retryRc >= 0)
                    {
                        McpLogger.Log("CppIndex", $"Retry OK: {Path.GetFileName(cmd2.File)}");
                    }
                    else if (retryRc == (int)NativeIndexer.IndexResult.ErrorStackOverflow)
                    {
                        stackOverflowTUs.Add(cmd2);
                    }
                    else
                    {
                        Interlocked.Increment(ref errors);
                        McpLogger.Log("CppIndex", $"Retry FAILED: {Path.GetFileName(cmd2.File)}", "ERROR");
                    }
                }
                McpLogger.Log("CppIndex", $"Sequential retry: {failedTUs.Count - retryErrors} recovered, {retryErrors} still failed");
            }

            // -- Large-stack retry for stack-overflow TUs --
            // LLVM's recursive descent parser can exceed the 1 MB ThreadPool
            // stack on TUs with deep include/template chains.  Retry on an
            // explicit thread with 8 MB stack.
            if (stackOverflowTUs.Count > 0)
            {
                McpLogger.Log("CppIndex",
                    $"Retrying {stackOverflowTUs.Count} stack-overflow TUs with 8 MB stack...", "WARN");
                foreach (var cmd3 in stackOverflowTUs)
                {
                    ct.ThrowIfCancellationRequested();
                    int soRetryRc = (int)NativeIndexer.IndexResult.ErrorGeneral;
                    using var soSession = new XrefSession(compileCommandsDir, _repoRoot);
                    var thread = new Thread(() =>
                    {
                        soRetryRc = IndexAndFlush(soSession, cmd3, tempDb, dbLock, ref errors);
                    }, maxStackSize: 8_388_608);
                    thread.Start();
                    thread.Join();

                    if (soRetryRc >= 0)
                        McpLogger.Log("CppIndex", $"Large-stack retry OK: {Path.GetFileName(cmd3.File)}");
                    else
                    {
                        Interlocked.Increment(ref errors);
                        McpLogger.Log("CppIndex",
                            $"Large-stack retry FAILED: {Path.GetFileName(cmd3.File)}", "ERROR");
                    }
                }
            }

            sw.Stop();
            var totalIndexed = _indexedFiles.Count;
            tempDb.SetProgress(totalIndexed, commands.Count);
            McpLogger.Log("CppIndex", $"Progress: {totalIndexed}/{commands.Count} ({errors} errors)");

            var (symCount, refCount, callCount) = tempDb.GetStats();
            tempDb.SetMeta("indexed_at", DateTime.UtcNow.ToString("O"));
            tempDb.SetMeta("file_count", commands.Count.ToString());
            tempDb.SetMeta("duration_sec", sw.Elapsed.TotalSeconds.ToString("F1"));
            tempDb.SetMeta("parallelism", parallelism.ToString());
            tempDb.SetMeta("indexer", "ClangXref/IndexDataConsumer");

            McpLogger.Log("CppIndex", $"Done in {sw.Elapsed.TotalSeconds:F1}s: " +
                $"{symCount} symbols, {refCount} refs, {callCount} calls ({errors} TU errors)");

            SwapDatabase(tempDb, tempDbPath);
        }
        catch (OperationCanceledException)
        {
            var totalIndexed = _indexedFiles.Count;
            McpLogger.Log("CppIndex", $"Cancelled at {totalIndexed}/{commands.Count} — saving partial index");
            tempDb.SetProgress(totalIndexed, commands.Count);
            SwapDatabase(tempDb, tempDbPath);
        }
        catch (Exception ex)
        {
            McpLogger.Log("CppIndex", $"Fatal error: {ex}", "FATAL");
            _db.MarkError(ex.Message);
            try { tempDb.Dispose(); } catch { }
        }

        // Clean up PCH files
        if (Directory.Exists(pchDir))
            try { Directory.Delete(pchDir, recursive: true); } catch { }
    }

    /// <summary>
    /// Atomic swap: close temp DB, close live DB, replace file, reopen.
    /// </summary>
    private void SwapDatabase(XrefDatabase tempDb, string tempDbPath)
    {
        tempDb.Dispose();
        _db.Close();
        SqliteConnection.ClearAllPools();
        var livePath = _db.DbPath;
        File.Move(tempDbPath, livePath, overwrite: true);

        foreach (var ext in new[] { "-wal", "-shm" })
        {
            var f = tempDbPath + ext;
            if (File.Exists(f)) try { File.Delete(f); } catch { }
        }

        _db.Open();
        _db.MarkReady();
        _db.LoadCallGraph();
    }

    /// <summary>
    /// Resolves a CompileCommand's file to an absolute path for the DLL.
    /// </summary>
    private string ResolveSourceFile(CompileCommand cmd)
    {
        return Path.IsPathRooted(cmd.File)
            ? cmd.File
            : Path.Combine(cmd.Directory ?? _repoRoot, cmd.File);
    }

    /// <summary>
    /// Index one TU and flush its results to the DB immediately.
    /// The dbLock serializes DB writes while parsing runs in parallel.
    /// Returns the DLL return code (>=0 = success, -1 = SEH, -2 = stack overflow).
    /// </summary>
    private int IndexAndFlush(XrefSession session, CompileCommand cmd,
        XrefDatabase db, object dbLock, ref int errors)
    {
        try
        {
            var sourceFile = ResolveSourceFile(cmd);
            var (result, returnCode) = session.IndexTu(sourceFile);
            if (result != null)
            {
                lock (dbLock)
                {
                    var txn = db.BeginTransaction();
                    db.BulkInsert(result);
                    txn.Commit();
                    txn.Dispose();
                }
                return returnCode;
            }
            return returnCode;  // negative: SEH crash or stack overflow
        }
        catch (Exception ex)
        {
            Interlocked.Increment(ref errors);
            McpLogger.Log("CppIndex", $"Error indexing {cmd.File}: {ex.Message}", "ERROR");
            return (int)NativeIndexer.IndexResult.ErrorGeneral;
        }
    }

    private List<CompileCommand> LoadCompileCommands()
    {
        var json = File.ReadAllText(_compileCommandsPath);
        return JsonSerializer.Deserialize<List<CompileCommand>>(json) ?? [];
    }

    private string NormalizeFilePath(string filePath)
    {
        var full = Path.IsPathRooted(filePath)
            ? filePath
            : Path.Combine(_repoRoot, filePath);
        return Path.GetFullPath(full).Replace('/', '\\');
    }
}

/// <summary>
/// Represents one entry in compile_commands.json.
/// </summary>
public sealed class CompileCommand
{
    [JsonPropertyName("directory")]
    public string? Directory { get; set; }

    [JsonPropertyName("file")]
    public string File { get; set; } = "";

    [JsonPropertyName("command")]
    public string? Command { get; set; }

    [JsonPropertyName("arguments")]
    public string[]? Arguments { get; set; }

    [JsonPropertyName("output")]
    public string? Output { get; set; }
}
